name: directory-listing

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Delete directory listings
        run: rm -rf **/index.html
        working-directory: scraper

      - name: Generate directory listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: scraper

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add scraper/

          git diff --cached --quiet || git commit -m "Update scraper listing"

          git push
